config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :projects
  root to: "projects#index"

  get 'contact' => 'static_pages#contact'
end

app/models/project.rb
class Project < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  # removed ':registerable' from below
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy, :edit, :update]
  before_action :set_project, only: [:edit, :update, :destroy, :show]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.save
    redirect_to projects_path
  end

  def edit
  end

  def update
    @project.update(project_params)
    redirect_to projects_path
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:title, :subhead, :description, :url, :picture)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <!-- Page Heading -->
        <div class="col-lg-12">
          <h1 class="page-header">Project Portfolio
            <small>Snapshots of Progress</small>
          </h1>
        </div>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project, html: { multipart: true}) do |f| %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :subhead %><br>
    <%= f.text_field :subhead, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :descrption %><br>
    <%= f.text_area(:description, class: 'form-control',
                    rows: '10', cols: '10')%>
  </div>
  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_field :url, class: 'form-control' %>
  </div>
  <div class="action">
    <%= f.submit class: "btn btn-primary" %>
  </div>
  <span class="picture">
    <%= f.file_field :picture %>
  </span>
<% end %>

app/views/projects/_project.html.erb
<hr>
<div class="row">
  <div class="col-md-7">
    <h3>Screen Shot</h3>
    <a href="http://<%= project.url %>">
      <%= image_tag(project.picture.url, class: 'img-responsive') if project.picture? %>
    </a>
  </div>
  <div class="col-md-5">
    <h3><%= project.title %></h3>
    <h4><%= project.subhead %></h4>
    <p><%= markdown(project.description) %></p>
    <a class="btn btn-primary" href="http://<%= project.url %>">View Project <span class="glyphicon glyphicon-chevron-right"></span></a>
    <% if current_user.present? %>
      <hr>
      <%= link_to "Edit", edit_project_path(project) %> |
      <%= link_to "Delete", project_path(project), method: :delete,
        data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
</div>

app/views/projects/_task.html.erb
<%= project.id %>
<%= project.title %>
<%= project.url %>
hello

app/views/projects/edit.html.erb
<%= form_for(@project) do |f| %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :subhead %><br>
    <%= f.text_field :subhead, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :descrption %><br>
    <%= f.text_area(:description, class: 'form-control')%>
  </div>
  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_field :url, class: 'form-control' %>
  </div>
  <div class="action">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/index.html.erb
<% if current_user.present? %>
  <%= link_to 'New Project', new_project_path %>
<% end %>
<div class="row">
  <div><%= render @projects %></div>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/shared/_footer.html.erb
<footer>
  <div class="row">
    <div class="col-lg-12">
      <p>Copyright &copy; JamesYoun.com 2015</p>
    </div>
  </div>
  <!-- /.row -->
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Portfolio</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <a href="http://jhy.herokuapp.com">Blog</a>
        </li>
        <li>
          <a href="/contact">Contact</a>
        </li>
        <% if user_signed_in? %>
          <li>
            <%= link_to 'Sign Out', destroy_user_session_path,
              method: :delete %>
        </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/static_pages/contact.html.erb
<div class="row">
  <div class="col-md-8">
    <h3>About James</h3>
    <p>I've been in the startup grind as a sales biz / dev guy for 6 years
    and have been making personal projects for about 2 years now.  Whether
    it be improving bottom lines or writing lines of code there's something
    immensely satisfying about creating something into existance.
    </p>
  </div>

  <div class="col-md-4">
    <h3>Contact Info</h3>
    <li><strong>Email:</strong> jamesyoun710 at gmail.com</li>
    <li><strong>Github: </strong><a href="http://github.com/eternal44">(click)</a></li>
    <li><strong>Linkedin: </strong><a href="http://www.linkedin.com/in/jamesyoun">(click)</a></li>

  </div>
</div><!--row-->

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>1 Col Portfolio - Start Bootstrap Template</title>

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Start Bootstrap</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <a href="#">About</a>
            </li>
            <li>
              <a href="#">Services</a>
            </li>
            <li>
              <a href="#">Contact</a>
            </li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

      <!-- Page Heading -->
      <div class="row">
        <div class="col-lg-12">
          <h1 class="page-header">Project Portfolio
            <small>Snapshots of Progress</small>
          </h1>
        </div>
      </div>
      <!-- /.row -->

      <!-- Project One -->
      <div class="row">
        <div class="col-md-7">
          <a href="#">
            <img class="img-responsive" src="http://placehold.it/700x300" alt="">
          </a>
        </div>
        <div class="col-md-5">
          <h3>Project One</h3>
          <h4>Subheading</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium veniam exercitationem expedita laborum at voluptate. Labore, voluptates totam at aut nemo deserunt rem magni pariatur quos perspiciatis atque eveniet unde.</p>
          <a class="btn btn-primary" href="#">View Project <span class="glyphicon" ></span></a>
        </div>
      </div>
      <!-- /.row -->

      <hr>

      <!-- Project Two -->
      <div class="row">
        <div class="col-md-7">
          <a href="#">
            <img class="img-responsive" src="http://placehold.it/700x300" alt="">
          </a>
        </div>
        <div class="col-md-5">
          <h3>Project Two</h3>
          <h4>Subheading</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, odit velit cumque vero doloremque repellendus distinctio maiores rem expedita a nam vitae modi quidem similique ducimus! Velit, esse totam tempore.</p>
          <a class="btn btn-primary" href="#">View Project <span class="glyphicon glyphicon-chevron-right"></span></a>
        </div>
      </div>
      <!-- /.row -->

      <hr>

      <!-- Project Three -->
      <div class="row">
        <div class="col-md-7">
          <a href="#">
            <img class="img-responsive" src="http://placehold.it/700x300" alt="">
          </a>
        </div>
        <div class="col-md-5">
          <h3>Project Three</h3>
          <h4>Subheading</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, temporibus, dolores, at, praesentium ut unde repudiandae voluptatum sit ab debitis suscipit fugiat natus velit excepturi amet commodi deleniti alias possimus!</p>
          <a class="btn btn-primary" href="#">View Project <span class="glyphicon glyphicon-chevron-right"></span></a>
        </div>
      </div>
      <!-- /.row -->

      <hr>

      <!-- Project Four -->
      <div class="row">

        <div class="col-md-7">
          <a href="#">
            <img class="img-responsive" src="http://placehold.it/700x300" alt="">
          </a>
        </div>
        <div class="col-md-5">
          <h3>Project Four</h3>
          <h4>Subheading</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo, quidem, consectetur, officia rem officiis illum aliquam perspiciatis aspernatur quod modi hic nemo qui soluta aut eius fugit quam in suscipit?</p>
          <a class="btn btn-primary" href="#">View Project <span class="glyphicon glyphicon-chevron-right"></span></a>
        </div>
      </div>
      <!-- /.row -->

      <hr>

      <!-- Project Five -->
      <div class="row">
        <div class="col-md-7">
          <a href="#">
            <img class="img-responsive" src="http://placehold.it/700x300" alt="">
          </a>
        </div>
        <div class="col-md-5">
          <h3>Project Five</h3>
          <h4>Subheading</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, quo, minima, inventore voluptatum saepe quos nostrum provident ex quisquam hic odio repellendus atque porro distinctio quae id laboriosam facilis dolorum.</p>
          <a class="btn btn-primary" href="#">View Project <span class="glyphicon glyphicon-chevron-right"></span></a>
        </div>
      </div>
      <!-- /.row -->

      <hr>

      <!-- Pagination -->
      <div class="row text-center">
        <div class="col-lg-12">
          <ul class="pagination">
            <li>
              <a href="#">&laquo;</a>
            </li>
            <li class="active">
              <a href="#">1</a>
            </li>
            <li>
              <a href="#">2</a>
            </li>
            <li>
              <a href="#">3</a>
            </li>
            <li>
              <a href="#">4</a>
            </li>
            <li>
              <a href="#">5</a>
            </li>
            <li>
              <a href="#">&raquo;</a>
            </li>
          </ul>
        </div>
      </div>
      <!-- /.row -->

      <hr>

      <!-- Footer -->
      <footer>
        <div class="row">
          <div class="col-lg-12">
            <p>Copyright &copy; Your Website 2014</p>
          </div>
        </div>
        <!-- /.row -->
      </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

  </body>

</html>